services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Callbacks
    NetGroup\UserGuide\Classes\Contao\Callbacks\LockHandler:
        tags:
            # tl_guides
            - { name: contao.callback, table: tl_guides, target: fields.locked.load, method: checkDatasetLocked, priority: 1024 }

            - { name: contao.callback, table: tl_guides, target: list.operations.edit.button, method: adjustOperations, priority: 2048 }
            - { name: contao.callback, table: tl_guides, target: list.operations.copy.button, method: adjustOperations, priority: 2048 }
            - { name: contao.callback, table: tl_guides, target: list.operations.delete.button, method: adjustOperations, priority: 2048 }

            # tl_manuals
            - { name: contao.callback, table: tl_manuals, target: fields.locked.load, method: checkDatasetLocked, priority: 1024 }

            - { name: contao.callback, table: tl_manuals, target: list.operations.editheader.button, method: adjustOperations, priority: 2048 }
            - { name: contao.callback, table: tl_manuals, target: list.operations.copy.button, method: adjustOperations, priority: 2048 }
            - { name: contao.callback, table: tl_manuals, target: list.operations.delete.button, method: adjustOperations, priority: 2048 }
            - { name: contao.callback, table: tl_manuals, target: list.operations.categories.button, method: adjustOperations, priority: 2048 }

            # tl_manual_categories
            - { name: contao.callback, table: tl_manual_categories, target: fields.title.load, method: checkDatasetLocked, priority: 1024 }

    NetGroup\UserGuide\Classes\Contao\Callbacks\TlManuals:
        arguments:
            $projectRoot: '%kernel.project_dir%'
        tags:
            - { name: contao.callback, table: tl_manuals, target: list.operations.edit.button, method: adjustIcon, priority: 1024 }

    NetGroup\UserGuide\Classes\Contao\Callbacks\TlGuides:
        tags:
            - { name: contao.callback, table: tl_guides, target: fields.category.options, method: loadCategories, priority: 1024 }
            - { name: contao.callback, table: tl_guides, target: list.label.label, method: createLabel, priority: 1024 }
            - { name: contao.callback, table: tl_guides, target: config.onload, method: addAssets, priority: 2048 }
            - { name: contao.callback, table: tl_guides, target: config.onload, method: checkPermissions, priority: 1024 }
            - { name: contao.callback, table: tl_guides, target: fields.icon.options, method: generateFontAwesomeOptions, priority: 1024 }

