services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Factories
    NetGroup\UserGuide\Classes\Services\Factories\TemplateFactory: ~

    NetGroup\UserGuide\Classes\Services\Factories\MarkdownFactory: ~


    # Helper
    NetGroup\UserGuide\Classes\Services\Helper\GuideRenderer:
        public: true

    NetGroup\UserGuide\Classes\Services\Helper\QueryHelper:
        arguments:
            $connection: '@database_connection'

#    NetGroup\UserGuide\Classes\Services\ExampleHelper:
#        arguments:
#            - '%kernel.project_dir%'
#            - '@database_connection'
#            - '%env(PROJECT_ENV_VARIABLE)%'
#            - '@request_stack'
#            - '@contao.routing.scope_matcher'
#            - '%contao.image.valid_extensions%'
